version: '3'

services:

  app:
    build:
      context: node
    container_name: app
    tty: true
    ports:
      - "3000:3000"
    entrypoint: wait-for db:3306 -t 40 -- node index.js
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=nodedb
    networks:
    - nodenet
    depends_on:
      - db

  db:
    image: mysql:8.0.32
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nodenet

  nginx:
    build:
      context: nginx
    container_name: nginx
    networks:
      - nodenet
    ports:
      - "8080:80"
    depends_on:
      - app

networks:
  nodenet:
    driver: bridge